// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jeokcwaellvizdaoywze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Implb2tjd2FlbGx2aXpkYW95d3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjk3ODIsImV4cCI6MjA1OTk0NTc4Mn0.vonLivCsxkdIDAIPsrELjag74vlOkPYlhFEEJr0CZYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});